name: alloy fmt

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  format:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Install Alloy CLI
      run: |
        curl -fsSL https://raw.githubusercontent.com/felixhummel/provision/refs/heads/main/alloy | bash

    - name: Run Alloy Format
      run: |
        alloy fmt config.alloy
